version: "3.3"  # optional since v1.27.0
services:
  nest:
    build: ./service3

  flask1:
    build: ./service1
    ports:
      - "8000:5000"
  flask2:
    build: ./service2
    ports:
      - "8001:5001"      

